control_points = [
    [
    -96.82786560058594,
    -33.941001892089844,
],
    [
    -110.2388916015625,
    -35.03273010253906,
],
    [
    -134.11050415039063,
    -24.27046775817871,
],
    [
    -136.90243530273438,
    19.207988739013672,
],
    [
    -139.9575653076172,
    68.90689086914063,
],
    [
    -116.6243896484375,
    65.726806640625,
],
    [
    -104.66109466552734,
    28.99744415283203,
],
    [
    -64.7496337890625,
    32.341094970703125,
],
    [
    -26.585350036621094,
    41.11688232421875,
],
    [
    -14.582168579101563,
    16.464372634887695,
],
    [
    -40.0220947265625,
    -8.788337707519531,
],
    [
    -81.92339324951172,
    16.07640838623047,
],
    [
    -108.68333435058594,
    16.865175247192383,
],
    [
    -118.32908630371094,
    -2.1254749298095703,
],
    [
    -113.54176330566406,
    -13.408893585205078,
],
    [
    -75.104736328125,
    -18.924758911132813,
],
    [
    5.475200653076172,
    -14.981067657470703,
],
    [
    33.04766845703125,
    -14.030181884765625,
],
    [
    34.23883056640625,
    6.141019821166992,
],
    [
    34.01244354248047,
    17.570249557495117,
],
    [
    25.75000762939453,
    21.352821350097656,
],
    [
    7.876308441162109,
    21.83907127380371,
],
    [
    -2.9265403747558594,
    21.446638107299805,
],
    [
    -6.094970703125,
    32.2892951965332,
],
    [
    -1.9661712646484375,
    53.36634063720703,
],
    [
    -61.43267059326172,
    52.28434371948242,
],
    [
    -97.92003631591797,
    54.261070251464844,
],
    [
    -91.46971893310547,
    83.41329956054688,
],
    [
    -63.76111602783203,
    80.08807373046875,
],
    [
    0.9364852905273438,
    69.27337646484375,
],
    [
    31.947486877441406,
    57.59307861328125,
],
    [
    39.364410400390625,
    82.62306213378906,
],
    [
    64.93529510498047,
    77.94642639160156,
],
    [
    62.0697021484375,
    57.22728729248047,
],
    [
    54.16401672363281,
    -10.5625,
],
    [
    53.7890739440918,
    -35.82086944580078,
],
    [
    29.14942169189453,
    -34.391815185546875,
],
]

[metadata]
name = "Untitled"
author = ""
track_width = 9.0
kerb_width = 0.5
