control_points = [
    [
    -77.16773223876953,
    -15.564929962158203,
],
    [
    -87.96101379394531,
    -15.393348693847656,
],
    [
    -101.45992279052734,
    -9.17630386352539,
],
    [
    -104.29180145263672,
    20.40843963623047,
],
    [
    -106.35965728759766,
    54.04662322998047,
],
    [
    -90.56682586669922,
    51.89421463012695,
],
    [
    -82.46958923339844,
    27.034332275390625,
],
    [
    -55.45591354370117,
    29.297447204589844,
],
    [
    -29.62481117248535,
    35.23725128173828,
],
    [
    -21.500581741333008,
    18.55144691467285,
],
    [
    -38.71933364868164,
    1.45941162109375,
],
    [
    -67.07978057861328,
    18.288860321044922,
],
    [
    -85.19200134277344,
    18.822731018066406,
],
    [
    -91.72062683105469,
    5.9691009521484375,
],
    [
    -88.48039245605469,
    -1.667959213256836,
],
    [
    -62.46466827392578,
    -5.401329040527344,
],
    [
    -7.924957275390625,
    -2.7320728302001953,
],
    [
    10.737186431884766,
    -2.0884838104248047,
],
    [
    11.316508293151855,
    12.168846130371094,
],
    [
    11.417105674743652,
    17.089542388916016,
],
    [
    9.706789016723633,
    20.43639373779297,
],
    [
    5.797847747802734,
    21.86014747619629,
],
    [
    -6.299787521362305,
    22.189260482788086,
],
    [
    -13.61158561706543,
    21.923646926879883,
],
    [
    -15.756109237670898,
    29.262386322021484,
],
    [
    -12.961565017700195,
    43.528167724609375,
],
    [
    -53.21086502075195,
    42.79583740234375,
],
    [
    -77.90696716308594,
    44.133750915527344,
],
    [
    -73.54110717773438,
    63.865142822265625,
],
    [
    -54.786842346191406,
    61.61448287963867,
],
    [
    -10.25867748260498,
    56.48995590209961,
],
    [
    9.992549896240234,
    46.38898468017578,
],
    [
    15.01259994506836,
    63.33027267456055,
],
    [
    32.32000732421875,
    60.16494369506836,
],
    [
    30.380462646484375,
    46.14140319824219,
],
    [
    25.02957534790039,
    0.2585887908935547,
],
    [
    25.73372459411621,
    -15.923608779907227,
],
    [
    8.098716735839844,
    -15.870037078857422,
],
]

[metadata]
name = "Untitled"
author = ""
track_width = 9.0
kerb_width = 0.5
