[package]
name = "emulator_game"
version = "0.1.0"
edition = "2024"


[dependencies]
bevy = "0.13.1"
bevy_rapier2d = "0.25.0"
iyes_perf_ui = "0.2.3"
noise = "0.9.0"
emulator_core = { path = "../core" }
